const categories = [
  {
    id: 1,
    name: 'Missing',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: false,
  },
  {
    id: 2,
    name: 'Eating',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 3,
    name: 'Groceries',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 4,
    name: 'Electronics',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 5,
    name: 'Shopping',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 6,
    name: 'Home Shopping',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 7,
    name: 'Rent',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 8,
    name: 'Energy',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 9,
    name: 'Public Transport',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 10,
    name: 'Taxi',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 11,
    name: 'Long Distance',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 12,
    name: 'Car Rental',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 13,
    name: 'Fuel',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 14,
    name: 'Parking',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 15,
    name: 'Fitness',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 16,
    name: 'Books',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 17,
    name: 'Hotel',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 18,
    name: 'TV Streaming',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 19,
    name: 'Internet',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 20,
    name: 'Mobile',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 21,
    name: 'Software',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 22,
    name: 'Fines',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 23,
    name: 'Insurence',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 24,
    name: 'Taxes',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 25,
    name: 'Investment',
    expenseType: 'OUT',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 26,
    name: 'Income',
    expenseType: 'IN',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 27,
    name: 'Refund',
    expenseType: 'IN',
    icon: null,
    userId: null,
    isVisible: true,
  },
  {
    id: 28,
    name: 'Sale',
    expenseType: 'IN',
    icon: null,
    userId: null,
    isVisible: true,
  },
];

exports.seed = (knex) => {
  return knex('Category')
    .del()
    .then(() => knex('Category').insert(categories));
};
