export default [
  {
    name: 'Missing',
    expenseType: 'OUT',
    icon: null,
    isVisible: false,
  },
  {
    name: 'Eating',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Groceries',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Electronics',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Shopping',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Home Shopping',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Rent',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Energy',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Public Transport',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Taxi',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Long Distance',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Car Rental',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Fuel',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Parking',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Fitness',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Books',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Hotel',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'TV Streaming',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Internet',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Mobile',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Software',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Fines',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Insurence',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Taxes',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Investment',
    expenseType: 'OUT',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Income',
    expenseType: 'IN',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Refund',
    expenseType: 'IN',
    icon: null,
    isVisible: true,
  },
  {
    name: 'Sale',
    expenseType: 'IN',
    icon: null,
    isVisible: true,
  },
];
